name: Copy to Docs

on:
  push:
    branches:
      - main

jobs:
  copy_to_docs:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Create docs directory
        run: mkdir -p docs

      - name: Copy files
        run: cp -a src/. docs/
